[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blueshift_anchor_vault = "8mDnY22HT7JHHbUmRDGSyCX6qp3CMZbokK7Z899zvsuN"

[programs.devnet]
blueshift_anchor_vault = "8mDnY22HT7JHHbUmRDGSyCX6qp3CMZbokK7Z899zvsuN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/dbm/.config/solana/id.json"

[test]
startup_wait = 30000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
